name: Build and Deploy to Azure Container App

on:
  push:
    branches: [test]

permissions:
  contents: write
  pull-requests: write

env:
  ACR_NAME: modernwebacr
  ACR_LOGIN_SERVER: modernwebacr.azurecr.io
  IMAGE_NAME: modernweb-api
  RESOURCE_GROUP: modern-web-rg
  TEST_CONTAINER_APP_NAME: modernweb-app
  PROD_CONTAINER_APP_NAME: modernweb-prod

jobs:
  build-and-deploy-test:
    name: Build and Deploy to TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        working-directory: ./backend
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Azure Container App (TEST)
        run: |
          az containerapp update \
            --name $TEST_CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

  deploy-prod:
    name: Deploy to PROD
    needs: build-and-deploy-test
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: https://modernweb-prod.azurecontainerapps.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App (PROD)
        run: |
          az containerapp update \
            --name $PROD_CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

  promote-to-main:
    name: Create PR from test → main
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: test
          destination_branch: main
          pr_title: "Promote stable version to main"
          pr_body: "This PR promotes commit `${{ github.sha }}` to `main` after successful production deployment."
          github_token: ${{ secrets.GITHUB_TOKEN }}
